import 'package:flutter/material.dart';
import 'package:flutter_tabler_icons/flutter_tabler_icons.dart';

/// 图标映射表
final Map<String, IconData> iconMap = {
  // 设置相关
  'language': Icons.language_outlined,
  'category': Icons.category_outlined,
  
  // 导航和位置
  'navigation': TablerIcons.navigation,
  'compass': TablerIcons.compass,
  'map': TablerIcons.map,
  'map_2': TablerIcons.map_2,
  'map_pin': TablerIcons.map_pin,
  'map_pins': TablerIcons.map_pins,
  'map_search': TablerIcons.map_search,
  'location': TablerIcons.location,
  'current_location': TablerIcons.current_location,
  'route': TablerIcons.route,
  'world': TablerIcons.world,
  'world_latitude': TablerIcons.world_latitude,
  'world_longitude': TablerIcons.world_longitude,
  'globe': TablerIcons.globe,
  'radar': TablerIcons.radar,
  'radar_2': TablerIcons.radar_2,

  // 交通工具
  'car': TablerIcons.car,
  'bus': TablerIcons.bus,
  'train': TablerIcons.train,
  'metro': TablerIcons.train,
  'bike': TablerIcons.bike,
  'walk': TablerIcons.walk,
  'run': TablerIcons.run,
  'plane': TablerIcons.plane,
  'plane_arrival': TablerIcons.plane_arrival,
  'plane_departure': TablerIcons.plane_departure,
  'helicopter': TablerIcons.helicopter,
  'ship': TablerIcons.ship,
  'motorbike': TablerIcons.motorbike,
  'scooter': TablerIcons.scooter,
  'truck': TablerIcons.truck,
  'ambulance': TablerIcons.ambulance,
  'firetruck': TablerIcons.firetruck,
  'emergency': TablerIcons.emergency_bed,

  // 地点和设施
  'home': TablerIcons.home,
  'building': TablerIcons.building,
  'building_arch': TablerIcons.building_arch,
  'building_bank': TablerIcons.building_bank,
  'building_church': TablerIcons.building_church,
  'building_hospital': TablerIcons.building_hospital,
  'building_store': TablerIcons.building_store,
  'school': TablerIcons.school,
  'hotel': TablerIcons.building_cottage,
  'restaurant': TablerIcons.tools_kitchen_2,
  'coffee': TablerIcons.coffee,
  'parking': TablerIcons.parking,
  'gas_station': TablerIcons.gas_station,
  'electric_station': TablerIcons.plug,
  'garden': TablerIcons.garden_cart,
  'pool': TablerIcons.pool,
  'beach': TablerIcons.beach,
  'mountain': TablerIcons.mountain,
  'park': TablerIcons.trees,

  // 界面和操作
  'menu': TablerIcons.menu_2,
  'search': TablerIcons.search,
  'settings': TablerIcons.settings,
  'filter': TablerIcons.filter,
  'sort': TablerIcons.sort_ascending,
  'list': TablerIcons.list,
  'grid': TablerIcons.grid_dots,
  'zoom_in': TablerIcons.zoom_in,
  'zoom_out': TablerIcons.zoom_out,
  'maximize': TablerIcons.maximize,
  'minimize': TablerIcons.minimize,
  'refresh': TablerIcons.refresh,
  'share': TablerIcons.share,
  'edit': TablerIcons.edit,
  'trash': TablerIcons.trash,
  'plus': TablerIcons.plus,
  'minus': TablerIcons.minus,
  'check': TablerIcons.check,
  'x': TablerIcons.x,
  'dots': TablerIcons.dots,

  // 天气
  'sun': TablerIcons.sun,
  'moon': TablerIcons.moon,
  'cloud': TablerIcons.cloud,
  'cloud_rain': TablerIcons.cloud_rain,
  'cloud_snow': TablerIcons.cloud_snow,
  'cloud_storm': TablerIcons.cloud_storm,
  'wind': TablerIcons.wind,
  'temperature': TablerIcons.temperature,
  'umbrella': TablerIcons.umbrella,

  // 状态和通知
  'alert': TablerIcons.alert_circle,
  'info': TablerIcons.info_circle,
  'help': TablerIcons.help,
  'notification': TablerIcons.bell,
  'connection': TablerIcons.antenna,
  'wifi': TablerIcons.wifi,
  'battery': TablerIcons.battery,
  'speed': TablerIcons.speedboat,
  'compass_direction': TablerIcons.direction,

  // 用户相关
  'user': TablerIcons.user,
  'users': TablerIcons.users,
  'user_circle': TablerIcons.user_circle,
  'login': TablerIcons.login,
  'logout': TablerIcons.logout,
  'key': TablerIcons.key,
  'lock': TablerIcons.lock,
  'shield': TablerIcons.shield,
  'star': TablerIcons.star,
  'heart': TablerIcons.heart,
  'bookmark': TablerIcons.bookmark,

  // 文件和文档
  'file': TablerIcons.file,
  'files': TablerIcons.files,
  'folder': TablerIcons.folder,
  'folder_plus': TablerIcons.folder_plus,
  'folder_minus': TablerIcons.folder_minus,
  'folder_open': TablerIcons.folder_open,
  'folder_filled': TablerIcons.folder_filled,
  'folder_x': TablerIcons.folder_x,
  'archive': TablerIcons.archive,
  'box': TablerIcons.box,
  'inbox': TablerIcons.inbox,
  'download': TablerIcons.download,
  'upload': TablerIcons.upload,
  'cloud_upload': TablerIcons.cloud_upload,
  'cloud_download': TablerIcons.cloud_download,
  'clipboard': TablerIcons.clipboard,
  'clipboard_check': TablerIcons.clipboard_check,
  'clipboard_list': TablerIcons.clipboard_list,

  // 通讯和社交
  'mail': TablerIcons.mail,
  'phone': TablerIcons.phone,
  'message': TablerIcons.message,
  'messages': TablerIcons.messages,
  'send': TablerIcons.send,
  'share_2': TablerIcons.share,
  'link': TablerIcons.link,
  'unlink': TablerIcons.unlink,
  'chat': TablerIcons.message_circle,
  'video': TablerIcons.video,
  'camera': TablerIcons.camera,
  'microphone': TablerIcons.microphone,
  'headphones': TablerIcons.headphones,
  'volume': TablerIcons.volume,
  'rss': TablerIcons.rss,

  // 商务和金融
  'briefcase': TablerIcons.briefcase,
  'calculator': TablerIcons.calculator,
  'chart': TablerIcons.chart_line,
  'pie_chart': TablerIcons.chart_pie,
  'bar_chart': TablerIcons.chart_bar,
  'trending_up': TablerIcons.trending_up,
  'trending_down': TablerIcons.trending_down,
  'coin': TablerIcons.coin,
  'coins': TablerIcons.coins,
  'currency_dollar': TablerIcons.currency_dollar,
  'currency_euro': TablerIcons.currency_euro,
  'credit_card': TablerIcons.credit_card,
  'receipt': TablerIcons.receipt,
  'report': TablerIcons.report,
  'presentation': TablerIcons.presentation,

  // 开发和技术
  'code': TablerIcons.code,
  'terminal': TablerIcons.terminal,
  'database': TablerIcons.database,
  'server': TablerIcons.server,
  'cpu': TablerIcons.cpu,
  'device_desktop': TablerIcons.device_desktop,
  'device_laptop': TablerIcons.device_laptop,
  'device_mobile': TablerIcons.device_mobile,
  'device_tablet': TablerIcons.device_tablet,
  'devices': TablerIcons.devices,
  'bug': TablerIcons.bug,
  'git_branch': TablerIcons.git_branch,
  'git_commit': TablerIcons.git_commit,
  'git_merge': TablerIcons.git_merge,
  'git_pull_request': TablerIcons.git_pull_request,

  // 媒体和娱乐
  'music': TablerIcons.music,
  'player_play': TablerIcons.player_play,
  'player_pause': TablerIcons.player_pause,
  'player_stop': TablerIcons.player_stop,
  'player_skip_forward': TablerIcons.player_skip_forward,
  'player_skip_back': TablerIcons.player_skip_back,
  'player_record': TablerIcons.player_record,
  'player_track_next': TablerIcons.player_track_next,
  'player_track_prev': TablerIcons.player_track_prev,
  'playlist': TablerIcons.playlist,
  'movie': TablerIcons.movie,
  'video_plus': TablerIcons.video_plus,
  'camera_plus': TablerIcons.camera_plus,
  'photo': TablerIcons.photo,
  'polaroid': TablerIcons.polaroid,

  // 其他
  'apps': TablerIcons.apps,
  'browser': TablerIcons.browser,
  'palette': TablerIcons.palette,
  'game': TablerIcons.device_gamepad,
  'shopping': TablerIcons.shopping_cart,
  'news': TablerIcons.news,
  'social': TablerIcons.users,
  'tag': TablerIcons.tag,
  'tags': TablerIcons.tags,
  'flag': TablerIcons.flag,
  'pin': TablerIcons.pin,
  'copy': TablerIcons.copy,
  'paste': TablerIcons.clipboard,
  'rotate': TablerIcons.rotate,
};

/// 图标分类
const Map<String, List<String>> iconCategories = {
  '导航': [
    'navigation',
    'compass',
    'map',
    'map_2',
    'map_pin',
    'map_search',
    'location',
    'current_location',
    'route',
    'world',
    'globe',
    'radar'
  ],
  '交通': [
    'car',
    'bus',
    'train',
    'metro',
    'bike',
    'walk',
    'plane',
    'plane_arrival',
    'plane_departure',
    'ship',
    'motorbike',
    'scooter'
  ],
  '地点': [
    'home',
    'building',
    'building_hospital',
    'building_store',
    'school',
    'hotel',
    'restaurant',
    'parking',
    'gas_station',
    'garden',
    'pool',
    'beach',
    'mountain',
    'park'
  ],
  '界面': [
    'menu',
    'search',
    'settings',
    'filter',
    'sort',
    'list',
    'grid',
    'zoom_in',
    'zoom_out',
    'refresh',
    'share',
    'edit',
    'trash',
    'plus',
    'minus',
    'check',
    'x',
    'dots'
  ],
  '天气': [
    'sun',
    'moon',
    'cloud',
    'cloud_rain',
    'cloud_snow',
    'cloud_storm',
    'wind',
    'temperature',
    'umbrella'
  ],
  '状态': [
    'alert',
    'info',
    'help',
    'notification',
    'connection',
    'wifi',
    'battery',
    'speed',
    'compass_direction'
  ],
  '用户': [
    'user',
    'users',
    'user_circle',
    'login',
    'logout',
    'key',
    'lock',
    'shield',
    'star',
    'heart',
    'bookmark'
  ],
  '文件': [
    'file',
    'files',
    'folder',
    'folder_plus',
    'folder_minus',
    'folder_open',
    'folder_filled',
    'folder_x',
    'archive',
    'box',
    'inbox',
    'download',
    'upload',
    'cloud_upload',
    'cloud_download',
    'clipboard',
    'clipboard_check',
    'clipboard_list'
  ],
  '通讯': [
    'mail',
    'phone',
    'message',
    'messages',
    'send',
    'share_2',
    'link',
    'unlink',
    'chat',
    'video',
    'camera',
    'microphone',
    'headphones',
    'volume',
    'rss'
  ],
  '商务': [
    'briefcase',
    'calculator',
    'chart',
    'pie_chart',
    'bar_chart',
    'trending_up',
    'trending_down',
    'coin',
    'coins',
    'currency_dollar',
    'currency_euro',
    'credit_card',
    'receipt',
    'report',
    'presentation'
  ],
  '开发': [
    'code',
    'terminal',
    'database',
    'server',
    'cpu',
    'device_desktop',
    'device_laptop',
    'device_mobile',
    'device_tablet',
    'devices',
    'bug',
    'git_branch',
    'git_commit',
    'git_merge',
    'git_pull_request'
  ],
  '媒体': [
    'music',
    'player_play',
    'player_pause',
    'player_stop',
    'player_skip_forward',
    'player_skip_back',
    'player_record',
    'player_track_next',
    'player_track_prev',
    'playlist',
    'movie',
    'video_plus',
    'camera_plus',
    'photo',
    'polaroid'
  ],
  '其他': [
    'apps',
    'browser',
    'palette',
    'game',
    'shopping',
    'news',
    'social',
    'tag',
    'tags',
    'flag',
    'pin',
    'copy',
    'paste',
    'rotate'
  ]
};

/// 获取图标数据
IconData getIconData(String name) {
  return iconMap[name] ?? iconMap['folder']!; // 如果找不到图标，返回默认文件夹图标
}

/// 常用图标列表（用于图标选择器）
final List<String> commonIcons = [
  'folder',
  'folder_filled',
  'apps',
  'browser',
  'cloud',
  'code',
  'book',
  'tool',
  'settings',
  'palette',
  'photo',
  'video',
  'music',
  'game',
  'shopping',
  'heart',
  'star',
  'link',
  'world',
  'home',
  'social',
  'news',
  'database',
  'shield',
  'search',
  'map',
  'calendar',
  'chart',
  'list',
  'grid',
  'tag',
  'box',
  'info',
];

/// 默认分类图标映射
const Map<String, String> defaultCategoryIcons = {
  'uncategorized': 'folder',  // 未分类
  'website_management': 'language',  // 网站管理
  'category_management': 'category',  // 分类管理
  'backup': 'backup',  // 备份
  'about': 'info',  // 关于
};
